# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/sdb1/projects/Csgo/HantaHook-linux

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/sdb1/projects/Csgo/HantaHook-linux

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/sdb1/projects/Csgo/HantaHook-linux/CMakeFiles /mnt/sdb1/projects/Csgo/HantaHook-linux//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/sdb1/projects/Csgo/HantaHook-linux/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HantaHook

# Build rule for target.
HantaHook: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HantaHook
.PHONY : HantaHook

# fast build rule for target.
HantaHook/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/build
.PHONY : HantaHook/fast

src/gui/gui.o: src/gui/gui.cpp.o
.PHONY : src/gui/gui.o

# target to build an object file
src/gui/gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/gui/gui.cpp.o
.PHONY : src/gui/gui.cpp.o

src/gui/gui.i: src/gui/gui.cpp.i
.PHONY : src/gui/gui.i

# target to preprocess a source file
src/gui/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/gui/gui.cpp.i
.PHONY : src/gui/gui.cpp.i

src/gui/gui.s: src/gui/gui.cpp.s
.PHONY : src/gui/gui.s

# target to generate assembly for a file
src/gui/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/gui/gui.cpp.s
.PHONY : src/gui/gui.cpp.s

src/gui/main_window.o: src/gui/main_window.cpp.o
.PHONY : src/gui/main_window.o

# target to build an object file
src/gui/main_window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/gui/main_window.cpp.o
.PHONY : src/gui/main_window.cpp.o

src/gui/main_window.i: src/gui/main_window.cpp.i
.PHONY : src/gui/main_window.i

# target to preprocess a source file
src/gui/main_window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/gui/main_window.cpp.i
.PHONY : src/gui/main_window.cpp.i

src/gui/main_window.s: src/gui/main_window.cpp.s
.PHONY : src/gui/main_window.s

# target to generate assembly for a file
src/gui/main_window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/gui/main_window.cpp.s
.PHONY : src/gui/main_window.cpp.s

src/gui/tabs/legitbot_tab.o: src/gui/tabs/legitbot_tab.cpp.o
.PHONY : src/gui/tabs/legitbot_tab.o

# target to build an object file
src/gui/tabs/legitbot_tab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/gui/tabs/legitbot_tab.cpp.o
.PHONY : src/gui/tabs/legitbot_tab.cpp.o

src/gui/tabs/legitbot_tab.i: src/gui/tabs/legitbot_tab.cpp.i
.PHONY : src/gui/tabs/legitbot_tab.i

# target to preprocess a source file
src/gui/tabs/legitbot_tab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/gui/tabs/legitbot_tab.cpp.i
.PHONY : src/gui/tabs/legitbot_tab.cpp.i

src/gui/tabs/legitbot_tab.s: src/gui/tabs/legitbot_tab.cpp.s
.PHONY : src/gui/tabs/legitbot_tab.s

# target to generate assembly for a file
src/gui/tabs/legitbot_tab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/gui/tabs/legitbot_tab.cpp.s
.PHONY : src/gui/tabs/legitbot_tab.cpp.s

src/hantahook.o: src/hantahook.cpp.o
.PHONY : src/hantahook.o

# target to build an object file
src/hantahook.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/hantahook.cpp.o
.PHONY : src/hantahook.cpp.o

src/hantahook.i: src/hantahook.cpp.i
.PHONY : src/hantahook.i

# target to preprocess a source file
src/hantahook.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/hantahook.cpp.i
.PHONY : src/hantahook.cpp.i

src/hantahook.s: src/hantahook.cpp.s
.PHONY : src/hantahook.s

# target to generate assembly for a file
src/hantahook.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/hantahook.cpp.s
.PHONY : src/hantahook.cpp.s

src/hook/find_interfaces.o: src/hook/find_interfaces.cpp.o
.PHONY : src/hook/find_interfaces.o

# target to build an object file
src/hook/find_interfaces.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/hook/find_interfaces.cpp.o
.PHONY : src/hook/find_interfaces.cpp.o

src/hook/find_interfaces.i: src/hook/find_interfaces.cpp.i
.PHONY : src/hook/find_interfaces.i

# target to preprocess a source file
src/hook/find_interfaces.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/hook/find_interfaces.cpp.i
.PHONY : src/hook/find_interfaces.cpp.i

src/hook/find_interfaces.s: src/hook/find_interfaces.cpp.s
.PHONY : src/hook/find_interfaces.s

# target to generate assembly for a file
src/hook/find_interfaces.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/hook/find_interfaces.cpp.s
.PHONY : src/hook/find_interfaces.cpp.s

src/hook/hook.o: src/hook/hook.cpp.o
.PHONY : src/hook/hook.o

# target to build an object file
src/hook/hook.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/hook/hook.cpp.o
.PHONY : src/hook/hook.cpp.o

src/hook/hook.i: src/hook/hook.cpp.i
.PHONY : src/hook/hook.i

# target to preprocess a source file
src/hook/hook.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/hook/hook.cpp.i
.PHONY : src/hook/hook.cpp.i

src/hook/hook.s: src/hook/hook.cpp.s
.PHONY : src/hook/hook.s

# target to generate assembly for a file
src/hook/hook.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/hook/hook.cpp.s
.PHONY : src/hook/hook.cpp.s

src/hook/hook_imgui.o: src/hook/hook_imgui.cpp.o
.PHONY : src/hook/hook_imgui.o

# target to build an object file
src/hook/hook_imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/hook/hook_imgui.cpp.o
.PHONY : src/hook/hook_imgui.cpp.o

src/hook/hook_imgui.i: src/hook/hook_imgui.cpp.i
.PHONY : src/hook/hook_imgui.i

# target to preprocess a source file
src/hook/hook_imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/hook/hook_imgui.cpp.i
.PHONY : src/hook/hook_imgui.cpp.i

src/hook/hook_imgui.s: src/hook/hook_imgui.cpp.s
.PHONY : src/hook/hook_imgui.s

# target to generate assembly for a file
src/hook/hook_imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/hook/hook_imgui.cpp.s
.PHONY : src/hook/hook_imgui.cpp.s

src/imgui/examples/imgui_impl_opengles3.o: src/imgui/examples/imgui_impl_opengles3.cpp.o
.PHONY : src/imgui/examples/imgui_impl_opengles3.o

# target to build an object file
src/imgui/examples/imgui_impl_opengles3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/imgui/examples/imgui_impl_opengles3.cpp.o
.PHONY : src/imgui/examples/imgui_impl_opengles3.cpp.o

src/imgui/examples/imgui_impl_opengles3.i: src/imgui/examples/imgui_impl_opengles3.cpp.i
.PHONY : src/imgui/examples/imgui_impl_opengles3.i

# target to preprocess a source file
src/imgui/examples/imgui_impl_opengles3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/imgui/examples/imgui_impl_opengles3.cpp.i
.PHONY : src/imgui/examples/imgui_impl_opengles3.cpp.i

src/imgui/examples/imgui_impl_opengles3.s: src/imgui/examples/imgui_impl_opengles3.cpp.s
.PHONY : src/imgui/examples/imgui_impl_opengles3.s

# target to generate assembly for a file
src/imgui/examples/imgui_impl_opengles3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/imgui/examples/imgui_impl_opengles3.cpp.s
.PHONY : src/imgui/examples/imgui_impl_opengles3.cpp.s

src/imgui/examples/libs/gl3w/GL/gl3w.o: src/imgui/examples/libs/gl3w/GL/gl3w.c.o
.PHONY : src/imgui/examples/libs/gl3w/GL/gl3w.o

# target to build an object file
src/imgui/examples/libs/gl3w/GL/gl3w.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/imgui/examples/libs/gl3w/GL/gl3w.c.o
.PHONY : src/imgui/examples/libs/gl3w/GL/gl3w.c.o

src/imgui/examples/libs/gl3w/GL/gl3w.i: src/imgui/examples/libs/gl3w/GL/gl3w.c.i
.PHONY : src/imgui/examples/libs/gl3w/GL/gl3w.i

# target to preprocess a source file
src/imgui/examples/libs/gl3w/GL/gl3w.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/imgui/examples/libs/gl3w/GL/gl3w.c.i
.PHONY : src/imgui/examples/libs/gl3w/GL/gl3w.c.i

src/imgui/examples/libs/gl3w/GL/gl3w.s: src/imgui/examples/libs/gl3w/GL/gl3w.c.s
.PHONY : src/imgui/examples/libs/gl3w/GL/gl3w.s

# target to generate assembly for a file
src/imgui/examples/libs/gl3w/GL/gl3w.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/imgui/examples/libs/gl3w/GL/gl3w.c.s
.PHONY : src/imgui/examples/libs/gl3w/GL/gl3w.c.s

src/imgui/imgui.o: src/imgui/imgui.cpp.o
.PHONY : src/imgui/imgui.o

# target to build an object file
src/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/imgui/imgui.cpp.o
.PHONY : src/imgui/imgui.cpp.o

src/imgui/imgui.i: src/imgui/imgui.cpp.i
.PHONY : src/imgui/imgui.i

# target to preprocess a source file
src/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/imgui/imgui.cpp.i
.PHONY : src/imgui/imgui.cpp.i

src/imgui/imgui.s: src/imgui/imgui.cpp.s
.PHONY : src/imgui/imgui.s

# target to generate assembly for a file
src/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/imgui/imgui.cpp.s
.PHONY : src/imgui/imgui.cpp.s

src/imgui/imgui_demo.o: src/imgui/imgui_demo.cpp.o
.PHONY : src/imgui/imgui_demo.o

# target to build an object file
src/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/imgui/imgui_demo.cpp.o
.PHONY : src/imgui/imgui_demo.cpp.o

src/imgui/imgui_demo.i: src/imgui/imgui_demo.cpp.i
.PHONY : src/imgui/imgui_demo.i

# target to preprocess a source file
src/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/imgui/imgui_demo.cpp.i
.PHONY : src/imgui/imgui_demo.cpp.i

src/imgui/imgui_demo.s: src/imgui/imgui_demo.cpp.s
.PHONY : src/imgui/imgui_demo.s

# target to generate assembly for a file
src/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/imgui/imgui_demo.cpp.s
.PHONY : src/imgui/imgui_demo.cpp.s

src/imgui/imgui_draw.o: src/imgui/imgui_draw.cpp.o
.PHONY : src/imgui/imgui_draw.o

# target to build an object file
src/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/imgui/imgui_draw.cpp.o
.PHONY : src/imgui/imgui_draw.cpp.o

src/imgui/imgui_draw.i: src/imgui/imgui_draw.cpp.i
.PHONY : src/imgui/imgui_draw.i

# target to preprocess a source file
src/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/imgui/imgui_draw.cpp.i
.PHONY : src/imgui/imgui_draw.cpp.i

src/imgui/imgui_draw.s: src/imgui/imgui_draw.cpp.s
.PHONY : src/imgui/imgui_draw.s

# target to generate assembly for a file
src/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/imgui/imgui_draw.cpp.s
.PHONY : src/imgui/imgui_draw.cpp.s

src/imgui/imgui_user.o: src/imgui/imgui_user.cpp.o
.PHONY : src/imgui/imgui_user.o

# target to build an object file
src/imgui/imgui_user.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/imgui/imgui_user.cpp.o
.PHONY : src/imgui/imgui_user.cpp.o

src/imgui/imgui_user.i: src/imgui/imgui_user.cpp.i
.PHONY : src/imgui/imgui_user.i

# target to preprocess a source file
src/imgui/imgui_user.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/imgui/imgui_user.cpp.i
.PHONY : src/imgui/imgui_user.cpp.i

src/imgui/imgui_user.s: src/imgui/imgui_user.cpp.s
.PHONY : src/imgui/imgui_user.s

# target to generate assembly for a file
src/imgui/imgui_user.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HantaHook.dir/build.make CMakeFiles/HantaHook.dir/src/imgui/imgui_user.cpp.s
.PHONY : src/imgui/imgui_user.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... HantaHook"
	@echo "... src/gui/gui.o"
	@echo "... src/gui/gui.i"
	@echo "... src/gui/gui.s"
	@echo "... src/gui/main_window.o"
	@echo "... src/gui/main_window.i"
	@echo "... src/gui/main_window.s"
	@echo "... src/gui/tabs/legitbot_tab.o"
	@echo "... src/gui/tabs/legitbot_tab.i"
	@echo "... src/gui/tabs/legitbot_tab.s"
	@echo "... src/hantahook.o"
	@echo "... src/hantahook.i"
	@echo "... src/hantahook.s"
	@echo "... src/hook/find_interfaces.o"
	@echo "... src/hook/find_interfaces.i"
	@echo "... src/hook/find_interfaces.s"
	@echo "... src/hook/hook.o"
	@echo "... src/hook/hook.i"
	@echo "... src/hook/hook.s"
	@echo "... src/hook/hook_imgui.o"
	@echo "... src/hook/hook_imgui.i"
	@echo "... src/hook/hook_imgui.s"
	@echo "... src/imgui/examples/imgui_impl_opengles3.o"
	@echo "... src/imgui/examples/imgui_impl_opengles3.i"
	@echo "... src/imgui/examples/imgui_impl_opengles3.s"
	@echo "... src/imgui/examples/libs/gl3w/GL/gl3w.o"
	@echo "... src/imgui/examples/libs/gl3w/GL/gl3w.i"
	@echo "... src/imgui/examples/libs/gl3w/GL/gl3w.s"
	@echo "... src/imgui/imgui.o"
	@echo "... src/imgui/imgui.i"
	@echo "... src/imgui/imgui.s"
	@echo "... src/imgui/imgui_demo.o"
	@echo "... src/imgui/imgui_demo.i"
	@echo "... src/imgui/imgui_demo.s"
	@echo "... src/imgui/imgui_draw.o"
	@echo "... src/imgui/imgui_draw.i"
	@echo "... src/imgui/imgui_draw.s"
	@echo "... src/imgui/imgui_user.o"
	@echo "... src/imgui/imgui_user.i"
	@echo "... src/imgui/imgui_user.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

